name: dbt CI build pipeline


on:
  push:
    branches:
      - main  

jobs:
  dbt_run:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code in the repo
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7
          pip install python-dotenv

      - name: Set up environment variables
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          
        run: |
          echo "DBT_PROFILE_DIR=$(pwd)" >> $GITHUB_ENV
          echo "DBT_TARGET=dev" >> $GITHUB_ENV
          echo "DBT_USER=$DBT_USER" >> $GITHUB_ENV
          echo "DBT_PASSWORD=$DBT_PASSWORD" >> $GITHUB_ENV
          echo "DBT_HOST=$DBT_HOST" >> $GITHUB_ENV
          echo "DBT_DATABASE=$DBT_DATABASE" >> $GITHUB_ENV

      - name: Check connexion
        run: dbt debug

      - name: Install project dependencies
        run: dbt deps

      - name:
        run: dbt build
name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7
   
     

      
   
