deltastore_dbt_transformation:
  target: dev
  outputs:
    dev:
      driver: ODBC Driver 17 for SQL Server
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: raw
      server: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 60293
      threads: 8
      type: sqlserver
      user: "{{ env_var('DBT_USER') }}"
      trust_cert: True

    prod:
      driver: ODBC Driver 17 for SQL Server
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: analytics
      server: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 60293
      threads: 8
      type: sqlserver
      user: "{{ env_var('DBT_USER') }}"
      trust_cert: True
