version: 2

sources:
  - name: old_store
    schema: old_store
    freshness:
      warn_after: {count: 1, period: day}
    loaded_at_field: updated_at

    tables:
      - name: customers
        description: "This is the customers table"
        freshness:
          warn_after: {count: 1, period: day}
        columns:
          - name: customer_id
            data_tests:
              - not_null
              - unique

      - name: orders
        description: "This is the orders table"
        freshness: null
        columns:
          - name: order_id 
            data_tests:
              - not_null
              - unique
          - name: order_date
            tests:
              - check_valid_dates
          
      - name: products
        description: "This is the products table"
        columns:
          - name: product_id 
            data_tests:
              - not_null
              - unique

      - name: order_items
        description: "This is the order_items table"
        freshness: null
        columns:
          - name: order_item_id 
            data_tests:
              - not_null
              - unique

      - name: payment
        description: "This is the payments table"
        freshness: null
        columns:
          - name: payment_id
            data_tests:
              - not_null
              - unique

      - name: suppliers
        description: "This is the suppliers table"
        freshness: null
        columns:
          - name: supplier_id 
            data_tests:
              - not_null
              - unique

      - name: reviews
        description: "This is the reviews table"
        freshness: null
        columns:
          - name: review_id 
            data_tests:
              - not_null
              - unique

  - name: new_store
    schema: new_store
    tables:
      - name: products
        description: "This table contains information about products"
        freshness:
          warn_after: {count: 1, period: day}
        columns: 
          - name: id
            data_tests:
              - unique 
              - not_null

      - name: users
        description: "This table contains information about users"
        columns:
          - name: id
            data_tests:
              - unique 
              - not_null
