name: dbt CI test pipeline

on:
  pull_request:
    branches:
      - main  
    paths:
        - 'deltastore_dbt_transformation/**'  
  
  workflow_dispatch: 

jobs:
  dbt_run:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7

      - name: Set up environment variables
        run: |
          echo "DBT_HOST=${{ secrets.DBT_HOST }}" >> $GITHUB_ENV
          echo "DBT_USER=${{ secrets.DBT_USER }}" >> $GITHUB_ENV
          echo "DBT_PASSWORD=${{ secrets.DBT_PASSWORD }}" >> $GITHUB_ENV
          echo "DBT_DATABASE=${{ secrets.DBT_DATABASE }}" >> $GITHUB_ENV

      - name: Create .dbt directory and profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "deltastore_dbt_transformation:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      driver: ODBC Driver 17 for SQL Server" >> ~/.dbt/profiles.yml
          echo "      database: $DBT_DATABASE" >> ~/.dbt/profiles.yml
          echo "      schema: raw" >> ~/.dbt/profiles.yml
          echo "      server: $DBT_HOST" >> ~/.dbt/profiles.yml
          echo "      user: $DBT_USER" >> ~/.dbt/profiles.yml
          echo "      password: $DBT_PASSWORD" >> ~/.dbt/profiles.yml
          echo "      port: 60293" >> ~/.dbt/profiles.yml
          echo "      threads: 8" >> ~/.dbt/profiles.yml
          echo "      type: sqlserver" >> ~/.dbt/profiles.yml
          echo "      trust_cert: True" >> ~/.dbt/profiles.yml

      - name: Verify profiles.yml
        run: cat ~/.dbt/profiles.yml

      - name: Change directory to dbt project
        run: cd deltastore_dbt_transformation && pwd

      - name: Check dbt connection
        run: |
          cd deltastore_dbt_transformation
          dbt debug
      
      - name: Install dbt project dependencies
        run: |
          cd deltastore_dbt_transformation
          dbt deps 
      
      - name: Test all models
        run: |
          cd deltastore_dbt_transformation
          dbt test 
