name: dbt CI test pipeline

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'deltastore_dbt_transformation/**'  # Run only when files change in this folder

  workflow_dispatch:  # Allows manual trigger

jobs:
  dbt_run:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7

      - name: Set up environment variables
        run: |
          echo "DBT_HOST=${{ secrets.DBT_HOST }}" >> $GITHUB_ENV
          echo "DBT_USER=${{ secrets.DBT_USER }}" >> $GITHUB_ENV
          echo "DBT_PASSWORD=${{ secrets.DBT_PASSWORD }}" >> $GITHUB_ENV
          echo "DBT_DATABASE=${{ secrets.DBT_DATABASE }}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          echo "DBT_HOST=$DBT_HOST"
          echo "DBT_USER=$DBT_USER"
          echo "DBT_DATABASE=$DBT_DATABASE"

      - name: Create dbt profiles directory
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          deltastore_dbt_transformation:
            target: dev
            outputs:
              dev:
                driver: ODBC Driver 17 for SQL Server
                database: $DBT_DATABASE
                schema: raw
                server: $DBT_HOST
                user: $DBT_USER
                password: $DBT_PASSWORD
                port: 60293
                threads: 8
                type: sqlserver
                trust_cert: True
          EOL
          echo "Profiles file created at ~/.dbt/profiles.yml"

      - name: Check dbt connection
        run: dbt debug 

      - name: Install dbt project dependencies
        run: dbt deps
      
      - name: Test all models
        run: dbt test
