name: dbt CI test pipeline

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'deltastore_dbt_transformation/**'  

  workflow_dispatch: 

jobs:
  dbt_run:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ensure correct Python version is used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7  # Install the specific dbt adapter for SQL Server

      - name: Set up environment variables
        run: |
          echo "DBT_HOST=${{ secrets.DBT_HOST }}" >> $GITHUB_ENV
          echo "DBT_USER=${{ secrets.DBT_USER }}" >> $GITHUB_ENV
          echo "DBT_PASSWORD=${{ secrets.DBT_PASSWORD }}" >> $GITHUB_ENV
          echo "DBT_DATABASE=${{ secrets.DBT_DATABASE }}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          echo "DBT_HOST=$DBT_HOST"
          echo "DBT_USER=$DBT_USER"
          echo "DBT_DATABASE=$DBT_DATABASE"

      - name: Change directory to the dbt project
        run: cd deltastore_dbt_transformation

      - name: Create dbt profiles directory
        run: |
          mkdir -p ~/.dbt  # Create .dbt folder in the home directory
          cat > ~/.dbt/profiles.yml <<EOL
          deltastore_dbt_transformation:
            target: dev
            outputs:
              dev:
                driver: ODBC Driver 17 for SQL Server
                database: $DBT_DATABASE
                schema: raw  # Change this to an existing schema if 'raw' is not valid
                server: $DBT_HOST
                user: $DBT_USER
                password: $DBT_PASSWORD
                port: 60293
                threads: 8
                type: sqlserver
                trust_cert: True

          EOL
          echo "Profiles file created at ~/.dbt/profiles.yml"

      - name: Display the content of profiles.yml
        run: cat ~/.dbt/profiles.yml

      - name: Check dbt connection
        run: |
          cd deltastore_dbt_transformation
          dbt debug
      
      - name: Install dbt project dependencies
        run: |
          cd deltastore_dbt_transformation
          dbt deps 
      
      - name: Test all models
        run: |
          cd deltastore_dbt_transformation
          dbt test 
