name: dbt CI test pipeline

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'deltastore_dbt_transformation/**'  
  workflow_dispatch: 

jobs:
  dbt_run:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7

      - name: Install ODBC Driver for SQL Server
        run: |
          sudo curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc > /dev/null
          echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev



      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          deltastore_dbt_transformation:
            target: dev
            outputs:
              dev:
                type: sqlserver
                driver: "ODBC Driver 17 for SQL Server"
                server: "${{ secrets.DBT_HOST }}"
                user: "${{ secrets.DBT_USER }}"
                password: "${{ secrets.DBT_PASSWORD }}"
                database: "${{ secrets.DBT_DATABASE }}"
                schema: raw
                port: 1433
                threads: 8
                trust_cert: True
          EOL

      - name: Verify dbt profiles.yml
        run: cat ~/.dbt/profiles.yml

      - name: Check dbt connection
        run: |
          cd deltastore_dbt_transformation
          dbt debug

      - name: Install dbt project dependencies
        run: |
          cd deltastore_dbt_transformation
          dbt deps 

      - name: Test all models
        run: |
          cd deltastore_dbt_transformation
          dbt test
