name: dbt CI test pipeline

on:
  pull_request:
    branches:
      - main  
    paths:
        - 'deltastore_dbt_transformation/**'  
  workflow_dispatch:

jobs:
  dbt_run:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install SQL Server using Particular action
        uses: Particular/install-sql-server-action@v1.2.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          sqlserver-version: 2019
          catalog: deltastore_db

      - name: Install sqlcmd
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

      - name: Verify sqlcmd installation
        run: |
          sqlcmd -? # Check if sqlcmd is correctly installed

      - name: Verify SQL Server connection string
        run: |
          echo "SQL Server connection string: $SQL_SERVER_CONNECTION_STRING"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver==1.8.7

      - name: Set up environment variables for dbt
        run: |
          echo "DBT_HOST=localhost" >> $GITHUB_ENV
          echo "DBT_USER=sa" >> $GITHUB_ENV
          echo "DBT_PASSWORD=TestPassword" >> $GITHUB_ENV
          echo "DBT_DATABASE=deltastore_db" >> $GITHUB_ENV
  
      - name: Verify environment variables
        run: |
          echo "DBT_HOST=$DBT_HOST"
          echo "DBT_USER=$DBT_USER"
          echo "DBT_DATABASE=$DBT_DATABASE"
  
      - name: Create profiles.yml for dbt
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          deltastore_dbt_transformation:
            target: dev
            outputs:
              dev:
                driver: ODBC Driver 17 for SQL Server
                server: '$DBT_HOST'
                user: '$DBT_USER'
                password: '$DBT_PASSWORD'
                database: '$DBT_DATABASE'
                schema: raw
                trust_cert: true
                type: sqlserver
                port: 1433
                threads: 8
                login_timeout: 120
          EOF
  
      - name: Verify profiles.yml creation
        run: cat ~/.dbt/profiles.yml
        
      - name: Check dbt connection
        run: |
          cd deltastore_dbt_transformation
          dbt debug --verbose

      - name: Install dbt project dependencies
        run: |
          cd deltastore_dbt_transformation
          dbt deps 

      - name: Test all models
        run: |
          cd deltastore_dbt_transformation
          dbt test
